# Generated by Django 3.1.2 on 2022-12-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0003_auto_20221214_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
