# Generated by Django 3.1.2 on 2022-12-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0006_auto_20221215_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='イメージ')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('memo', models.CharField(blank=True, default='', max_length=255, verbose_name='メモ')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AddField(
            model_name='image',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbyapp.work', verbose_name='作品'),
        ),
    ]
