# Generated by Django 3.1.2 on 2022-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0007_auto_20221215_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='work',
        ),
        migrations.AddField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
