# Generated by Django 3.1.2 on 2022-12-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0008_auto_20221215_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
