# Generated by Django 3.1.2 on 2022-12-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0010_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
